export { default as ConnectDetailImageBox } from './ConnectDetailImageBox'
export { default as ConnectDetailShareBox } from './ConnectDetailShareBox'
export { default as ConnectDetailSocialBox } from './ConnectDetailSocialBox'
export { default as ConnectDetailTagBox } from './ConnectDetailTagBox'
export { default as ConnectDetailPersonalDataBox } from './ConnectDetailPersonalDataBox'
